[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ['@openzeppelin/contracts=lib/openzeppelin-contracts/contracts']
fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.release]
via_ir = true
optimizer = true
optimizer_runs = 200


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
